package za.ac.cput.FactoryTest;

import org.junit.jupiter.api.Test;
import za.ac.cput.domain.CartItem;
import za.ac.cput.factory.CartItemFactory;

import static org.junit.jupiter.api.Assertions.*;

import static org.junit.jupiter.api.Assertions.assertThrows;

public class CartItemFactoryTest {
    @Test
    void createCartItem_shouldReturnValidCartItem_withAutoGeneratedId() {

        CartItem cartItem = CartItemFactory.createCartItem("PROD-001", 2, 29.99);


        assertNotNull(cartItem);
        assertNotNull(cartItem.getCartItemId());
        assertTrue(cartItem.getCartItemId().startsWith("ITEM-"));
        assertEquals("PROD-001", cartItem.getProductId());
        assertEquals(2, cartItem.getQuantity());
        assertEquals(59.98, cartItem.getLineTotal());
    }

    @Test
    void createCartItem_shouldThrowException_whenProductIdIsNull() {
        assertThrows(IllegalArgumentException.class, () -> {
            CartItemFactory.createCartItem(null, 2, 29.99);
        });
    }

    @Test
    void createCartItem_shouldThrowException_whenProductIdIsEmpty() {
        assertThrows(IllegalArgumentException.class, () -> {
            CartItemFactory.createCartItem("", 2, 29.99);
        });
    }

    @Test
    void createCartItem_shouldThrowException_whenProductIdHasOnlySpaces() {
        assertThrows(IllegalArgumentException.class, () -> {
            CartItemFactory.createCartItem("   ", 2, 29.99);
        });
    }

    @Test
    void createCartItem_shouldThrowException_whenQuantityIsZero() {
        assertThrows(IllegalArgumentException.class, () -> {
            CartItemFactory.createCartItem("PROD-001", 0, 29.99);
        });
    }

    @Test
    void createCartItem_shouldThrowException_whenQuantityIsNegative() {
        assertThrows(IllegalArgumentException.class, () -> {
            CartItemFactory.createCartItem("PROD-001", -2, 29.99);
        });
    }

    @Test
    void createCartItem_shouldThrowException_whenUnitPriceIsZero() {
        assertThrows(IllegalArgumentException.class, () -> {
            CartItemFactory.createCartItem("PROD-001", 2, 0);
        });
    }

    @Test
    void createCartItem_shouldThrowException_whenUnitPriceIsNegative() {
        assertThrows(IllegalArgumentException.class, () -> {
            CartItemFactory.createCartItem("PROD-001", 2, -5.99);
        });
    }

    @Test
    void createCartItem_shouldCalculateCorrectLineTotal() {

        CartItem cartItem = CartItemFactory.createCartItem("PROD-001", 3, 15.50);
        assertEquals(46.50, cartItem.getLineTotal());
    }

    @Test
    void createCartItem_shouldCalculateLineTotalCorrectly_forDifferentValues() {
        // Act
        CartItem item1 = CartItemFactory.createCartItem("PROD-001", 1, 29.99);
        CartItem item2 = CartItemFactory.createCartItem("PROD-002", 5, 19.99);
        CartItem item3 = CartItemFactory.createCartItem("PROD-003", 10, 9.99);


        assertEquals(29.99, item1.getLineTotal(), 0.01);
        assertEquals(99.95, item2.getLineTotal(), 0.01);
        assertEquals(99.90, item3.getLineTotal(), 0.01);
    }
    @Test
    void createCartItem_shouldGenerateUniqueIds() {

        CartItem item1 = CartItemFactory.createCartItem("PROD-001", 1, 29.99);
        CartItem item2 = CartItemFactory.createCartItem("PROD-002", 1, 39.99);


        assertNotEquals(item1.getCartItemId(), item2.getCartItemId());
    }

    @Test
    void createCartItem_shouldGenerateIdWithCorrectFormat() {

        CartItem cartItem = CartItemFactory.createCartItem("PROD-001", 2, 29.99);


        assertTrue(cartItem.getCartItemId().matches("ITEM-\\d{8}-\\d{5}"));
    }

    @Test
    void updateQuantity_shouldReturnUpdatedCartItem() {

        CartItem original = CartItemFactory.createCartItem("PROD-001", 2, 29.99);
        String originalId = original.getCartItemId();
        String originalProductId = original.getProductId();


        CartItem updated = CartItemFactory.updateQuantity(original, 5, 29.99);


        assertEquals(5, updated.getQuantity());
        assertEquals(149.95, updated.getLineTotal());
        assertEquals(originalId, updated.getCartItemId());
        assertEquals(originalProductId, updated.getProductId());
    }

    @Test
    void updateQuantity_shouldThrowException_whenCartItemIsNull() {
        assertThrows(IllegalArgumentException.class, () -> {
            CartItemFactory.updateQuantity(null, 5, 29.99);
        });
    }

    @Test
    void updateQuantity_shouldThrowException_whenNewQuantityIsZero() {
        CartItem original = CartItemFactory.createCartItem("PROD-001", 2, 29.99);

        assertThrows(IllegalArgumentException.class, () -> {
            CartItemFactory.updateQuantity(original, 0, 29.99);
        });
    }

    @Test
    void updateQuantity_shouldThrowException_whenNewQuantityIsNegative() {
        CartItem original = CartItemFactory.createCartItem("PROD-001", 2, 29.99);

        assertThrows(IllegalArgumentException.class, () -> {
            CartItemFactory.updateQuantity(original, -5, 29.99);
        });
    }

    @Test
    void updateQuantity_shouldThrowException_whenUnitPriceIsZero() {
        CartItem original = CartItemFactory.createCartItem("PROD-001", 2, 29.99);

        assertThrows(IllegalArgumentException.class, () -> {
            CartItemFactory.updateQuantity(original, 5, 0);
        });
    }

    @Test
    void updateQuantity_shouldThrowException_whenUnitPriceIsNegative() {
        CartItem original = CartItemFactory.createCartItem("PROD-001", 2, 29.99);

        assertThrows(IllegalArgumentException.class, () -> {
            CartItemFactory.updateQuantity(original, 5, -10.00);
        });
    }

    @Test
    void updateQuantity_shouldCalculateCorrectLineTotal() {

        CartItem original = CartItemFactory.createCartItem("PROD-001", 2, 29.99);


        CartItem updated = CartItemFactory.updateQuantity(original, 10, 29.99);


        assertEquals(299.90, updated.getLineTotal());
    }

    @Test
    void updateQuantity_shouldPreserveCartItemId() {

        CartItem original = CartItemFactory.createCartItem("PROD-001", 2, 29.99);


        CartItem updated = CartItemFactory.updateQuantity(original, 10, 29.99);


        assertEquals(original.getCartItemId(), updated.getCartItemId());
    }

    @Test
    void updateQuantity_shouldPreserveProductId() {

        CartItem original = CartItemFactory.createCartItem("PROD-001", 2, 29.99);


        CartItem updated = CartItemFactory.updateQuantity(original, 10, 29.99);


        assertEquals(original.getProductId(), updated.getProductId());
    }
}
